### ISSUE TITLE
Python 3 bug in image summaries during plt.imshow

### ISSUE THREAD

**Issue by ecr05** [DLTK/DLTK#14]
Running the train.py from MRBrainS13_segmentation throws the following error during plt.imshow in summaries.py

File "train.py", line 278, in <module>
    train(args)
  File "train.py", line 231, in train
    sv.summary_computed(s, modules.image_summary(val_x[0], 'val_img'), global_step=step)
  File "....summaries.py", line 90, in image_summary
    plt.imsave(s, img[slicer], format='png')
...
...
    _png.write_png(im, fname)
TypeError: string argument expected, got 'bytes'

This is the second time I've run into a ' string argument expected, got 'bytes'' error with Python 3. It seems to be solved by replacing StringIO() with BytesIO() throughout summaries.py - see

https://stackoverflow.com/questions/32075135/python-3-in-memory-zipfile-error-string-argument-expected-got-bytes

**Comment by mrajchl** [comment]
Thanks for reporting. Should be resolved in v0.2
