### ISSUE TITLE
Python 3 _read_sample str/bytes conversion error

### ISSUE THREAD

**Issue by ecr05** [DLTK/DLTK#15]
Taking train.py from MRBrainS13_segmentation MRBrainS13_segmentation as an example. Training and validation data are read in as arrays of strings, but somewhere the training data is converted to an array of bytes. This is (I assume) why in _read_sample the pathnames are converted back from bytes to strings using path_list[0].decode('UTF-8'), but for Python 3 anyway, I'm finding this causes an error when reading validation paths, which remain as strings. I've hacked a solution to _read_sample as:

path_list = id_queue[0]
        
        if(isinstance(path_list[0],(bytes))): ## hack until I find why DLTK is converting string to bytes
            path_list_dir=path_list[0].decode('UTF-8')
        else:
            path_list_dir=path_list[0]

        # Use a SimpleITK reader to load the multi channel nii images and labels for training 
        t1 = sitk.GetArrayFromImage(sitk.ReadImage(os.path.join(str(path_list_dir), 'T1.nii')))
        t1_ir = sitk.GetArrayFromImage(sitk.ReadImage(os.path.join(str(path_list_dir), 'T1_IR.nii')))
        t2_fl = sitk.GetArrayFromImage(sitk.ReadImage(os.path.join(str(path_list_dir), 'T2_FLAIR.nii')))
        lbl = sitk.GetArrayFromImage(sitk.ReadImage(os.path.join(str(path_list_dir), 'LabelsForTraining.nii')))

**Comment by mrajchl** [comment]
Hey, thank you for pointing that out. This should be resolved in v0.2.
