### ISSUE TITLE
Dice computation in case truth label is missing

### ISSUE THREAD

**Issue by mrajchl** [DLTK/DLTK#21]
I'll open this issue to reference an outdated PR eaa94766cd40e1cac1f39569a733495314d1270e . The question is what the return value should be in case the truth label is missing in that example. 

Typically, it should return NaN (as in convert3d), however this complicates most applications and it is currently (suboptimally) handled like this for metrics:
https://github.com/DLTK/DLTK/blob/d8aeee9dd83e6f257dec2f1ef449f2bebfb5d316/dltk/core/metrics.py#L26

I suggest handling this as in dltk.core.losses: 
https://github.com/DLTK/DLTK/blob/d8aeee9dd83e6f257dec2f1ef449f2bebfb5d316/dltk/core/losses.py#L104

I'll leave this issue open for discussion until resolved.

**Comment by bglocker** [comment]
I think NaN would be the right thing to do. Is Tensorboard happy with NaNs?

**Comment by pawni** [comment]
solved by #28 . And TB should be happy with NaNs.
