### ISSUE TITLE
Segmentation with 2 modalities

### ISSUE THREAD

**Issue by ChuanWang90** [DLTK/DLTK#22]
Hi, I am trying to modify the example of the segmentation for 2 modalities. 

In train I have modified the number of channels to 2, and in the reader

`'x_train, y_train = reader.MRBrainsReader([tf.float32, tf.int32], [[24, 64, 64, 2], [24, 64, 64]], name='train_queue')(
            train_files, batch_size=batch_size, n_examples=18, min_queue_examples=batch_size * 2, capacity=batch_size * 4)'` 

In the mrbrains_reader I have modified this:

`data = self._preprocess([t1,t2_fl])` 

However I get this error.
 Tensor must be 4-D with last dim 1, 3, or 4, not [10,64,64,2]

I have tried with only one modality and it works. Could you please sir tell me what to modify?

Thanking you, Chuan.

**Comment by pawni** [comment]
Hi there,

sorry for not getting back earlier. Christmas got a little bit in the way. For smaller issues, please think about referring to Gitter ( gitter.im/dltk/dltk ).

It seem like you're using an old version of DLTK. If possible I would advise to adapt the current codebase.

Could you please post more information about your problem (full stack trace, code) ? I believe you try to have a Tensorboard image summary with the 2 channel data. Then Tensorflow throws an error that looks pretty much like yours (`Tensor must be 4-D with last dim 1, 3, or 4, not [10,64,64,2]`).

Best,
Nick

**Comment by ChuanWang90** [comment]
Dear sir,

thank you very much for your reply. As you suggested I updated to the last DLTK version. I made some changes to use one or two modalities only but still get some errors.

What I changed is, in train.py (from examples/applications/MRBrains):
`NUM_CHANNELS = 2`

And then comment this line:
`#my_image_summaries['feat_t2_flair'] = features['x'][0, 0, :, :, 2]`

And then in file 'reader.py' I stack only two image modalities:
`images = np.stack([t1, t1_ir], axis=-1).astype(np.float32)`

But still I miss something, because I get an error related with the number of channels when the training starts:

tensorflow.python.framework.errors_impl.InvalidArgumentError: Assign requires shapes of both tensors to match. lhs shape= [3,3,3,2,16] rhs shape= [3,3,3,3,16]

Could you please sir tell me what else I have to change?

Thanking you sir. Chuan.

**Comment by pawni** [comment]
Hi Chuan,

Could you please post full stack traces next time?

However, I believe this error could be caused by an old checkpoint. To check this either run training with `--restart` to overwrite the old checkpoint or with `-p /path/to/new/checkpoint/directory` to save the checkpoint for this run in a different directory.

Best,
Nick
