### ISSUE TITLE
download_IXI_HH.py fails to read images

### ISSUE THREAD

**Issue by keegansmith21** [DLTK/DLTK#25]
When I run "download_IXI_HH.py" I ran into an error when reading the images (line 150). I discovered that this occurred because the file paths were not being read as strings. I manually changed this and the code ran properly. I have attached the modified file:

[download_IXI_HH.txt](https://github.com/DLTK/DLTK/files/1990873/download_IXI_HH.txt)

**Comment by mrajchl** [comment]
Hi @keegansmith21, 

thanks for submitting the bug. Could you please let us know under which conditions the error occured (i.e. operating system, python version, tensorflow version)? That would help us to reproduce the issue.

**Comment by keegansmith21** [comment]
Hi, I ran the script on both my personal computer and a cluster.

My PC:
OS - Ubuntu 16.04
Python - 2.7.14
Tensorflow - 1.3.0

Cluster:
I'm unsure how to check the OS of the cluster
Python - 2.7.5
Tensorlfow - 1.4.1

The exact error message (the same in both cases):

Traceback (most recent call last):
  File "download_IXI_HH.py", line 150, in <module>
    t1 = sitk.ReadImage(t1_fn)
  File "/media/keegan/43379bb7-2565-4466-8a93-aa969ea76c5d/keegan/Anaconda2/lib/python2.7/site-packages/SimpleITK/SimpleITK.py", line 8614, in ReadImage
    return _SimpleITK.ReadImage(*args)
NotImplementedError: Wrong number or type of arguments for overloaded function 'ReadImage'.
  Possible C/C++ prototypes are:
    itk::simple::ReadImage(std::vector< std::string,std::allocator< std::string > > const &,itk::simple::PixelIDValueEnum)
    itk::simple::ReadImage(std::string const &,itk::simple::PixelIDValueEnum)

Hope this helps!
-Keegan

**Comment by mrajchl** [comment]
Hi Keegan, 

thanks a lot for reporting this. I've added a statement to the README.md file, that in the future, we will not be supporting python2 anymore (similarly to NumPy and SciPy). I'd suggest using python3 for this problem, which should avoid that.
