### ISSUE TITLE
GPU Memory Argument in MRBrains?

### ISSUE THREAD

**Issue by kmader** [DLTK/DLTK#4]
The GPU memory argument does not seem to be used anywhere in the MRBrains segmentation example. Is there something I missed?

https://github.com/DLTK/DLTK/blob/0f49afaec3e1174bed8ab8605312391fe3e933f3/examples/MRBrainS13_segmentation/train.py#L258

**Comment by mrajchl** [comment]
Thank you for pointing this out. This is legacy code that was not removed. This has been fixed in c711d15.
