### ISSUE TITLE
How could I find file "demographic_HH.csv"?

### ISSUE THREAD

**Issue by koalary** [DLTK/DLTK#40]

**Comment by koalary** [comment]
How could I find file "demographic_HH.csv"?

**Comment by mrajchl** [comment]
Hi there,
the file is generated by the data download script in this line: 
https://github.com/DLTK/DLTK/blob/master/data/IXI_HH/download_IXI_HH.py#L133

Please refer to the readme file https://github.com/DLTK/DLTK/blob/master/README.md, "Start Playing" point 1. If you have questions, please ask them in our gitter chat. 

Closing this, as it is not an issue.
