### ISSUE TITLE
Saliency/activation map

### ISSUE THREAD

**Issue by schmidje** [DLTK/DLTK#41]
Hi,

First of all thanks for contributing such a nice framework, this is very appreciated!

I have been playing with the example IXI_HH_sex_classification_resnet and I wonder if you would have any pointer on how I could produce saliency/activation maps which highlight in a test image what where the main areas of interest for the classification problem.

This is not an issue per se : )

Thanks a lot!

Best regards

**Comment by mrajchl** [comment]
Hi there, 
I don't know if these references are up to date, but I would suggest any approaches summarised in [1]. It think this can be a good start to read up on and try some simple baseline. I will close this, as this is not an issue, but please visit us in the gitter chat if you have more questions. 

[1] Baumgartner et al. Visual Feature Attribution Using Wasserstein GANs. CVPR 2018
