### ISSUE TITLE
How can I map my fMRI voxels to MNI

### ISSUE THREAD

**Issue by Student-HXJ** [DLTK/DLTK#43]
Hi, can DLTK convert fMRI data to MNI standard space,
Thank you in advance!

**Comment by mrajchl** [comment]
Hi, 
no, this is a machine learning, not a registration package. How about any of these: 
https://mirtk.github.io/
https://github.com/KCL-BMEIS/niftyreg

Closing this as this is not an issue. Feel free to drop by in our chat. https://gitter.im/DLTK/DLTK

HTH,
M
