### ISSUE TITLE
a question related to Lung Nodule Malignancy(LNM) dataset in kaggle

### ISSUE THREAD

**Issue by ShihuaiXu** [DLTK/DLTK#44]
Dear Professor Kevin：
I am confused about that whether the Lung Nodule Malignancy dataset contains the nodule of benign and malignancy? Could I understand the part of benign as the pircture has no nodule? And the part of malignancy contains picture which has nodule? Thank you in advance.
Warm regards Bill from China.

**Comment by mrajchl** [comment]
Hi Bill, 
I am not certain this refers to any contributor or has anything to do with DLTK. Closing this for now. If I am however incorrect, please come visit us in our gitter chat. 
Best,
Martin
