### ISSUE TITLE
Assert Syntax Incorrect

### ISSUE THREAD

**Issue by ericspod** [DLTK/DLTK#8]
I've encountered in a number of cases the syntax for the assert statement is incorrect and therefore are not being checked. An assert is a statement and not a function, it should be of the form "assert C [, M]" where C is a condition and M an optional message. 

In a number of places the syntax "assert (C,M)" is used which equates to the tuple (C,M) being used as the condition expression. Non-empty tuples always evaluate to True thus these assert statements always succeed and never check C. 

If the syntax "assert (C)" is used instead then (C) is an expression rather than a tuple and is correctly checked in that instance however I would say is still bad style.

**Comment by pawni** [comment]
Thanks for pointing that out, I guess I am the cause of most of those misused statements. You're welcome to submit a PR for changes, otherwise we'll get on it and fix it.

**Comment by ericspod** [comment]
I haven't got a PR ready i'm afraid, you probably will want to go through them and make sure they're to your style anyway.

**Comment by pawni** [comment]
Should be resolved by 461b312 . Thanks again for pointing that out.

**Comment by ericspod** [comment]
Great thanks for that. I've put up a pull request for a few more and one other bug I found, plus an issue with an example that's a separate matter.
